version: '3.1'
services:
    shortener:
        image: twrutniak/shortener:1.0
        ports:
            - "80:8000"
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017 

    mongo:
        image: mongo:3-xenial
        expose: 
            - 27017
        volumes:
            - ./db-data:/data/db