version: '3.1'
services:
    shortener:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:8000"
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017 

    mongo:
        image: mongo:3-xenial
        expose: 
            - 27017
        volumes:
            - ./db-data:/data/db

    nginx:
        image: nginx:1.19.2-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/var/www/static
            